# site
url: https://rickyzhangca.github.io/project-farm-results/
author: Ricky Zhang
title: "Project Farm Results"

# markdown
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-loading-lazy

# other configs
exclude: ["CNAME", "README.md"]
